name: GdUnit4 Tests
on: [push, pull_request]

permissions:
  id-token: write
  contents: read
  checks: write
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: MikeSchulze/gdunit4-action@v1.1.5
        with:
          godot-version: '4.4'
          godot-status: 'stable'
          paths: 'res://test'
          publish-report: false
